//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.22 at 07:13:59 PM IST 
//


package driver;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerGroups">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustomerGroupDetails" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="GroupManagerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Customers">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Customer" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Vandalism" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="MinimumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="MaximumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RentalRequests">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Request" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerGroups"
})
@XmlRootElement(name = "CustomersGroups")
public class CustomersGroups {

    @XmlElement(name = "CustomerGroups", required = true)
    protected CustomersGroups.CustomerGroups customerGroups;

    /**
     * Gets the value of the customerGroups property.
     * 
     * @return
     *     possible object is
     *     {@link CustomersGroups.CustomerGroups }
     *     
     */
    public CustomersGroups.CustomerGroups getCustomerGroups() {
        return customerGroups;
    }

    /**
     * Sets the value of the customerGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomersGroups.CustomerGroups }
     *     
     */
    public void setCustomerGroups(CustomersGroups.CustomerGroups value) {
        this.customerGroups = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomerGroupDetails" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="GroupManagerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Customers">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Customer" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Vandalism" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="MinimumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="MaximumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RentalRequests">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Request" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerGroupDetails"
    })
    public static class CustomerGroups {

        @XmlElement(name = "CustomerGroupDetails")
        protected List<CustomersGroups.CustomerGroups.CustomerGroupDetails> customerGroupDetails;

        /**
         * Gets the value of the customerGroupDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customerGroupDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomerGroupDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CustomersGroups.CustomerGroups.CustomerGroupDetails }
         * 
         * 
         */
        public List<CustomersGroups.CustomerGroups.CustomerGroupDetails> getCustomerGroupDetails() {
            if (customerGroupDetails == null) {
                customerGroupDetails = new ArrayList<CustomersGroups.CustomerGroups.CustomerGroupDetails>();
            }
            return this.customerGroupDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="GroupManagerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Customers">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Customer" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Vandalism" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="MinimumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="MaximumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RentalRequests">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Request" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "groupManagerName",
            "customers",
            "rentalRequests"
        })
        public static class CustomerGroupDetails {

            @XmlElement(name = "GroupManagerName", required = true)
            protected String groupManagerName;
            @XmlElement(name = "Customers", required = true)
            protected CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers customers;
            @XmlElement(name = "RentalRequests", required = true)
            protected CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests rentalRequests;

            /**
             * Gets the value of the groupManagerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGroupManagerName() {
                return groupManagerName;
            }

            /**
             * Sets the value of the groupManagerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGroupManagerName(String value) {
                this.groupManagerName = value;
            }

            /**
             * Gets the value of the customers property.
             * 
             * @return
             *     possible object is
             *     {@link CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers }
             *     
             */
            public CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers getCustomers() {
                return customers;
            }

            /**
             * Sets the value of the customers property.
             * 
             * @param value
             *     allowed object is
             *     {@link CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers }
             *     
             */
            public void setCustomers(CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers value) {
                this.customers = value;
            }

            /**
             * Gets the value of the rentalRequests property.
             * 
             * @return
             *     possible object is
             *     {@link CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests }
             *     
             */
            public CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests getRentalRequests() {
                return rentalRequests;
            }

            /**
             * Sets the value of the rentalRequests property.
             * 
             * @param value
             *     allowed object is
             *     {@link CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests }
             *     
             */
            public void setRentalRequests(CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests value) {
                this.rentalRequests = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Customer" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Vandalism" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="MinimumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="MaximumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "customer"
            })
            public static class Customers {

                @XmlElement(name = "Customer")
                protected List<CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers.Customer> customer;

                /**
                 * Gets the value of the customer property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the customer property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCustomer().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers.Customer }
                 * 
                 * 
                 */
                public List<CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers.Customer> getCustomer() {
                    if (customer == null) {
                        customer = new ArrayList<CustomersGroups.CustomerGroups.CustomerGroupDetails.Customers.Customer>();
                    }
                    return this.customer;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Vandalism" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="MinimumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="MaximumDamage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "vandalism",
                    "minimumDamage",
                    "maximumDamage"
                })
                public static class Customer {

                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "Vandalism", required = true)
                    protected String vandalism;
                    @XmlElement(name = "MinimumDamage")
                    protected byte minimumDamage;
                    @XmlElement(name = "MaximumDamage")
                    protected byte maximumDamage;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the vandalism property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getVandalism() {
                        return vandalism;
                    }

                    /**
                     * Sets the value of the vandalism property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setVandalism(String value) {
                        this.vandalism = value;
                    }

                    /**
                     * Gets the value of the minimumDamage property.
                     * 
                     */
                    public byte getMinimumDamage() {
                        return minimumDamage;
                    }

                    /**
                     * Sets the value of the minimumDamage property.
                     * 
                     */
                    public void setMinimumDamage(byte value) {
                        this.minimumDamage = value;
                    }

                    /**
                     * Gets the value of the maximumDamage property.
                     * 
                     */
                    public byte getMaximumDamage() {
                        return maximumDamage;
                    }

                    /**
                     * Sets the value of the maximumDamage property.
                     * 
                     */
                    public void setMaximumDamage(byte value) {
                        this.maximumDamage = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Request" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "request"
            })
            public static class RentalRequests {

                @XmlElement(name = "Request")
                protected List<CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests.Request> request;

                /**
                 * Gets the value of the request property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the request property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getRequest().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests.Request }
                 * 
                 * 
                 */
                public List<CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests.Request> getRequest() {
                    if (request == null) {
                        request = new ArrayList<CustomersGroups.CustomerGroups.CustomerGroupDetails.RentalRequests.Request>();
                    }
                    return this.request;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "type",
                    "size",
                    "duration"
                })
                public static class Request {

                    @XmlElement(name = "Type", required = true)
                    protected String type;
                    @XmlElement(name = "Size")
                    protected byte size;
                    @XmlElement(name = "Duration")
                    protected byte duration;
                    @XmlAttribute(name = "id")
                    protected Byte id;

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the size property.
                     * 
                     */
                    public byte getSize() {
                        return size;
                    }

                    /**
                     * Sets the value of the size property.
                     * 
                     */
                    public void setSize(byte value) {
                        this.size = value;
                    }

                    /**
                     * Gets the value of the duration property.
                     * 
                     */
                    public byte getDuration() {
                        return duration;
                    }

                    /**
                     * Sets the value of the duration property.
                     * 
                     */
                    public void setDuration(byte value) {
                        this.duration = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setId(Byte value) {
                        this.id = value;
                    }

                }

            }

        }

    }

}
