//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 05:02:48 PM IST 
//


package driver;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the driver package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: driver
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link REIT }
     * 
     */
    public REIT createREIT() {
        return new REIT();
    }

    /**
     * Create an instance of {@link REIT.Staff }
     * 
     */
    public REIT.Staff createREITStaff() {
        return new REIT.Staff();
    }

    /**
     * Create an instance of {@link REIT.Staff.Clerks }
     * 
     */
    public REIT.Staff.Clerks createREITStaffClerks() {
        return new REIT.Staff.Clerks();
    }

    /**
     * Create an instance of {@link REIT.Staff.Clerks.Clerk }
     * 
     */
    public REIT.Staff.Clerks.Clerk createREITStaffClerksClerk() {
        return new REIT.Staff.Clerks.Clerk();
    }

    /**
     * Create an instance of {@link REIT.Warehouse }
     * 
     */
    public REIT.Warehouse createREITWarehouse() {
        return new REIT.Warehouse();
    }

    /**
     * Create an instance of {@link REIT.Warehouse.Materials }
     * 
     */
    public REIT.Warehouse.Materials createREITWarehouseMaterials() {
        return new REIT.Warehouse.Materials();
    }

    /**
     * Create an instance of {@link REIT.Warehouse.Tools }
     * 
     */
    public REIT.Warehouse.Tools createREITWarehouseTools() {
        return new REIT.Warehouse.Tools();
    }

    /**
     * Create an instance of {@link REIT.Staff.Clerks.Clerk.Location }
     * 
     */
    public REIT.Staff.Clerks.Clerk.Location createREITStaffClerksClerkLocation() {
        return new REIT.Staff.Clerks.Clerk.Location();
    }

    /**
     * Create an instance of {@link REIT.Warehouse.Materials.Material }
     * 
     */
    public REIT.Warehouse.Materials.Material createREITWarehouseMaterialsMaterial() {
        return new REIT.Warehouse.Materials.Material();
    }

    /**
     * Create an instance of {@link REIT.Warehouse.Tools.Tool }
     * 
     */
    public REIT.Warehouse.Tools.Tool createREITWarehouseToolsTool() {
        return new REIT.Warehouse.Tools.Tool();
    }

}
